-- Enum değerleri (ayrı transaction — PG kısıtı)
ALTER TYPE "AppointmentStatus" ADD VALUE IF NOT EXISTS 'PENDING_BUSINESS_APPROVAL';
ALTER TYPE "AppointmentStatus" ADD VALUE IF NOT EXISTS 'APPROVED';
ALTER TYPE "AppointmentStatus" ADD VALUE IF NOT EXISTS 'REJECTED';
ALTER TYPE "AppointmentStatus" ADD VALUE IF NOT EXISTS 'RESCHEDULE_PROPOSED';
ALTER TYPE "AppointmentStatus" ADD VALUE IF NOT EXISTS 'RESCHEDULE_ACCEPTED';
ALTER TYPE "AppointmentStatus" ADD VALUE IF NOT EXISTS 'NO_SHOW';
ALTER TYPE "AppointmentStatus" ADD VALUE IF NOT EXISTS 'CANCELLED_BY_CUSTOMER';
ALTER TYPE "AppointmentStatus" ADD VALUE IF NOT EXISTS 'CANCELLED_BY_BUSINESS';
ALTER TYPE "AppointmentStatus" ADD VALUE IF NOT EXISTS 'EXPIRED';

ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'APPOINTMENT_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'APPOINTMENT_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'APPOINTMENT_RESCHEDULE';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'APPOINTMENT_REMINDER';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'APPOINTMENT_EXPIRED';
